name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # NOVO PASSO: Adiciona o scanner de vulnerabilidades
      - name: Analise de Vulnerabilidades com Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'meu-app-flask:latest' # NOME DA IMAGEM
          format: 'table'
          exit-code: '1' # Falha o pipeline se encontrar vulnerabilidades
          ignore-unfixed: true

      - name: Build e Push da imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meu-app-flask:latest
